Added palindrome checker in kotlin
TheRenegadeCoder/sample-programs pull request #2080
Opened 2020-10-03 10:16 UTC by anohene1

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][1]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

## Complete the Applicable Sections Below

Find which section best describes your pull request and make sure you fill it out. To start, let us know which issue you've fixed.

- [ ] I fixed #your-issue-number-here

### Code Snippets

- [ ] I named the pull request using `Added/Updated <Sample Program> in <Language>` format
- [ ] I created/updated the language README
  - [ ] I added the sample program name to the README
  - [ ] I added fun facts (i.e. debut developer, typing, etc.)
  - [ ] I added reference link(s) to the README
  - [ ] I added solution citations when necessary (see [plagiarism][2])

### Testing

- [ ] I named the pull request using `Added/Updated <Language>/<Project> Testing` format
- [ ] I followed the testinfo template, if applicable

## Notes

Feel free to describe what you added or updated.

[1]: https://therenegadecoder.com/
[2]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism

2020-10-07 03:28 UTC, jrg94 requested changes
We don't currently support palindrome, but we're open to including this if we can get it documented. Let me know if that's something you want to do!

2020-10-07 08:37 UTC, anohene1 commented
Sure. I'll do that. Let me know where to document it.

2020-10-07 15:34 UTC, jrg94 commented
Check out this repo: https://github.com/TheRenegadeCoder/sample-programs-website

You'll want to create something that looks like one of these: https://sample-programs.therenegadecoder.com/projects/

2020-10-07 19:01 UTC, anohene1 commented
I have done that and made a pull request. You can check it at https://github.com/TheRenegadeCoder/sample-programs-website/pull/349

2020-10-07 21:54 UTC, jrg94 commented
Cool! Now we have the specification, let's get some tests going. There's a bit of a dependency in our way at the moment. See #2186. That said, we can add the test file here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/test

2020-10-07 22:02 UTC, anohene1 commented
I'm sorry I don't get you quite well. Should the test be in python? As I can see all the test files are written in python.

2020-10-07 22:05 UTC, jrg94 commented
Yes! But the test files are more or less copy-and-paste. You should be able to copy binary-search.py and reuse most of it.

2020-10-07 22:06 UTC, anohene1 commented
Okay I'll go ahead and try that. I'll let you know if I'm done.

2020-10-07 22:18 UTC, anohene1 commented
This is getting very difficult for me as I have no knowledge in python.

2020-10-07 22:29 UTC, jrg94 commented
No worries! I can give you a rough idea of what you need to do. First, I'd copy the contents of the binary search test.

2020-10-07 22:30 UTC, jrg94 commented
Then, replace BinarySearch with PalindromicNumbers.

2020-10-07 22:30 UTC, jrg94 commented
Then, at the top of the file, you should see these: 

```
invalid_permutations = (
    'description,in_params,expected', [
        (
            'no input',
            None,
            'Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")'
        ), (
            'missing input: target',
            '"1, 2, 3, 4"',
            'Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")'
        ), (
            'missing input: list',
            '"" "5"',
            'Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")'
        ), (
            'out of order input',
            '"3, 5, 1, 2" "3"',
            'Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")'
        )
    ]
)

valid_permutations = (
    'description,in_params,expected', [
        (
            'sample input first true',
            '"1, 3, 5, 7" "1"',
            'true'
        ), (
            'sample input last true',
            '"1, 3, 5, 7" "7"',
            'true'
        ), (
            'sample input middle true',
            '"1, 3, 5, 7" "5"',
            'true'
        ), (
            'sample input one true',
            '"5" "5"',
            'true'
        ), (
            'sample input one false',
            '"5" "7"',
            'false'
        ), (
            'sample input many false',
            '"1, 3, 5, 6" "7"',
            'false'
        )
    ]
)
```

2020-10-07 22:32 UTC, jrg94 commented
These are the tests. You need to replace these tests with the one's you wrote. For example, the first invalid test looks like this: 

```
(
            'no input',
            None,
            'Usage: please provide a list of sorted integers ("1, 4, 5, 11, 12") and the integer to find ("11")'
)
```

You can replace it with this:

```
(
            'no input',
            None,
            'Usage: please input a number'
)
```

2020-10-07 22:48 UTC, anohene1 commented
I have finished editing the test file. You may check and let me know what else I need to do please.

2020-10-07 23:17 UTC, jrg94 requested changes
Looks good so far!

2020-10-07 23:17 UTC, jrg94 commented on test/projects/test_palindromic_number.py
> +            None,
```suggestion
            "",
```

2020-10-07 23:17 UTC, jrg94 commented on test/projects/test_palindromic_number.py
> +            None,
```suggestion
            "a",
```

2020-10-07 23:17 UTC, jrg94 commented on test/projects/test_palindromic_number.py
> +def test_palindromic_number_valid(description, in_params, expected, binary_search):
```suggestion
def test_palindromic_number_valid(description, in_params, expected, palindromic_number):
```

2020-10-07 23:17 UTC, jrg94 commented on test/projects/test_palindromic_number.py
> +def test_palindromic_number_invalid(description, in_params, expected, binary_search):
```suggestion
def test_palindromic_number_invalid(description, in_params, expected, palindromic_number):
```

2020-10-07 23:17 UTC, jrg94 commented
After this, you'll need to update both of these:

- https://github.com/TheRenegadeCoder/sample-programs/blob/master/runner.py
- https://github.com/TheRenegadeCoder/sample-programs/blob/master/.glotter.yml

2020-10-08 06:26 UTC, anohene1 commented
I have made both updates

2020-10-08 14:39 UTC, jrg94 requested changes
Looks good! The only issue is the program you wrote will fail your own tests. We don't have a way to prove that just yet because someone is currently adding Kotlin testing.

2020-10-08 14:44 UTC, anohene1 commented
Okay. So what do I do now?

2020-10-08 15:17 UTC, jrg94 commented
Update the Kotlin script to match your tests. Then, we're stuck waiting on #2186.

2020-10-08 15:53 UTC, anohene1 commented
I have fixed that.

2020-10-08 16:22 UTC, jrg94 approved these changes
I'm not sure your program matches your tests, but we'll go ahead and merge it for now. When Kotlin testing is implemented, we'll clean things up.

2020-10-08 16:44 UTC, merged