Add Convex Hull in C
TheRenegadeCoder/sample-programs pull request #3958
Opened 2024-10-28 23:53 UTC by 2Clutch

## I Am Adding a New Code Snippet in an Existing Language

- [x] I fixed #3295
- [x] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format

2024-10-29 00:06 UTC, rzuckerm requested changes
The error message needs to match the [project page](https://sampleprograms.io/projects/convex-hull/).

2024-10-29 00:21 UTC, rzuckerm commented
See [this](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11564593566/job/32190077650?pr=3958#step:7:2943) for the test failures.

2024-10-29 00:33 UTC, 2Clutch commented
> See [this](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11564593566/job/32190077650?pr=3958#step:7:2943) for the test failures.

I have a good idea of how to navigate this now so I should be fine (I hope). I have a solution in place for all of the issues I was assigned, and I'm now refactoring and making sure it follows the project description to the letter.

I don't want to start over so I suspect each PR will have 1 or 2 failures before going through.

2024-10-29 12:39 UTC, rzuckerm requested changes
The tests are still failing. See [this](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11565182047/job/32191764069?pr=3958#step:7:2943) for details. Also, please review the [project page](https://sampleprograms.io/projects/convex-hull/) again. The inputs are a list of X-coordinates and a list of Y-coordinates. The number of X- and Y-coordinates must be the same, and there must be at least 3 of them.

2024-10-29 20:32 UTC, rzuckerm requested changes
Something about your parsing algorithm is incorrect since there are errors like `Invalid Integers` for valid inputs. Please see [this](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11581572902/job/32242651150#step:7:2983) for details

2024-10-29 20:32 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +    printf("The points in the convex hull are:\n");
This `printf` needs to be removed

2024-10-29 20:32 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +    }
The error message for both of these should be this:
```
Usage: please provide at least 3 x and y coordinates as separate lists (e.g. "100, 440, 210")
```

2024-10-29 20:32 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +    }
Not sure this is actually needed since the number of coordinates was checked before calling this function.

2024-10-29 20:50 UTC, rzuckerm requested changes

2024-10-29 20:50 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +        if (*s < '0' || *s > '9') {
Negative numbers need to be handled

2024-10-29 20:50 UTC, rzuckerm commented on archive/c/c/convex-hull.c
>          printf("Different Cardinality\n");
The error message still needs to display the usage message.

2024-10-29 20:50 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +        printf("Usage: please provide two coordinate lists (x, y)\n");
The error message needs to be this for all cases:
```
Usage: please provide at least 3 x and y coordinates as separate lists (e.g. "100, 440, 210")
```

2024-10-29 20:50 UTC, rzuckerm commented on archive/c/c/convex-hull.c
> +        printf("Missing Y\n");
Same comment here

2024-10-29 22:18 UTC, rzuckerm requested changes
The parsing still isn't right. The usage error message is being shown for all the cases. See [this](https://github.com/TheRenegadeCoder/sample-programs/actions/runs/11582362465/job/32245234628#step:7:2983)

2024-11-16 14:30 UTC, rzuckerm approved these changes
@2Clutch I used your parsing from Binary Search to fix this.

2024-11-16 14:30 UTC, merged