Created longest-word program
TheRenegadeCoder/sample-programs pull request #4020
Opened 2024-11-12 05:44 UTC by TavSingh

Congrats on taking the first step to contributing to the Sample Programs repository maintained by [The Renegade Coder][renegade-coder]! 
For simplicity, please make sure that your pull request includes one and only one contribution.

Please fill _one_ of the sections below as applicable.
Please also add any other relevant information to the Notes section at the bottom.
You may delete or just ignore any other sections.
For more information please refer to our [contributing documentation][contributing]

## I Am Adding a New Code Snippet in an Existing Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
  
  
## I Am Adding a New Code Snippet in a New Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} in {LANGUAGE}` format
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
  

## I Am Adding New Tests for a Project

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {PROJECT} Tests` format
- [ ] I verified the project exists on the [Sample Programs Project List][sample-programs-project-list]
- [ ] I added tests for every test case in the Testing table of the project description for the given project. (See [contributing documentation][contributing-tests-in-detail])

## I Am Adding New Tests for a Language

- [ ] I fixed #your-issue-number-here
- [ ] I named the pull request using `Add {LANGUAGE} Tests` format
- [ ] I added a `testinfo.yml` files (see [contributing documentation][contributing-new-language])
  - [ ] I used an officially supported docker image or one that I personally trust
- [ ] I verified all tests are passing

  
## I Am Modifying an Existing Code Snippet or Existing Tests

- [ ] I fixed #your-issue-number-here
- [ ] I have read about modifying existing code snippets or tests in the [contributing documentation][contributing-modifications]
- [ ] I have explained why this modification is _necessary_ either in the issue linked above or in the notes below
- [ ] I named the pull request using `Modify {PROJECT} {tests} in {LANGUAGE}` format

## Other Notes

Add notes here...

[renegade-coder]: https://therenegadecoder.com/
[contributing-plagiarism]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#plagiarism
[contributing-new-project]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-project
[contributing-new-language]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#requirements-for-a-new-language
[contributing-readme]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#create-readmes
[contributing-tests-in-detail]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#tests-in-detail
[contributing]: CONTRIBUTING.md
[sample-programs-project-list]: https://sampleprograms.io/projects/
[contributing-modifications]: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#modifying-existing-code-snippets

2024-11-12 13:29 UTC, rzuckerm requested changes
Please remove the extra files. The only file that should be in the pull request is `longest-word.R`

2024-11-14 21:03 UTC, TavSingh commented
Extra files have been removed

2024-11-14 22:11 UTC, rzuckerm requested changes

2024-11-14 22:11 UTC, rzuckerm commented on archive/r/r/longest-word.R
> +longest_word_length()
This needs to accept a command-line argument. Please see the [project documentation](https://sampleprograms.io/projects/longest-word/)

2024-11-21 21:33 UTC, TavSingh commented
Accepts command line noq

2024-11-21 22:43 UTC, rzuckerm approved these changes
Looks good, @TavSingh . Thanks for your contribution!

2024-11-21 22:44 UTC, merged